version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/book-0.0.1-SNAPSHOT.war book.war
artifacts:
  files:
    - book.war
    - .ebextensions/**/*